FROM postgres
COPY init.sql /docker-entrypoint-initdb.d/10-init.sql
COPY bbb.sh /bbb.sh
WORKDIR /

RUN apt update
RUN apt install -y wget curl postgresql-plperl-16
RUN apt install -y make libdbix-safe-perl libboolean-perl libdbd-mock-perl libdbd-pg-perl libanyevent-dbd-pg-perl libpg-hstore-perl libpgobject-perl libpod-parser-perl libencode-locale-perl
RUN wget -q https://bucardo.org/downloads/Bucardo-5.6.0.tar.gz
RUN tar xf Bucardo-5.6.0.tar.gz

RUN cd Bucardo-5*/ && perl Makefile.PL && make install
RUN mkdir -p /var/run/bucardo /var/log/bucardo
RUN touch /var/log/bucardo/log.bucardo



